config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root :to =>"homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    #検索モデル→params[:range]
    @range = params[:range]

    if @range == "User"
      #検索方法→params[:search]
      @users = User.looks(params[:search], params[:word])
      #@user = User.find(params[:id])
    else
      #検索ワード→params[:word]
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

# ②if文を使い、検索モデルUserorBookで条件分岐させます。

# ③looksメソッドを使い、検索内容を取得し、変数に代入します。
# 検索方法params searchと、検索ワードparams[:word]を参照してデータを検索し、
# 1：インスタンス変数@usersにUserモデル内での検索結果を代入します。
# 2：インスタンス変数@booksにBookモデル内での検索結果を代入します。

# これでsearchアクションは完成です。

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_serach.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

<!--url: search_path-->
<!--検索内容を、先ほど作成したルーティングに送信します。-->

<!--<%#= f.text_field :word %>-->
<!--検索内容を、wordとしてアクションに送っています。-->

<!--<%#= f.select :range, options_for_select([['User'], ['Book']]) %>-->
<!--今回は複数のモデルを検索できるように実装する為、-->
<!--__Userモデル__と__Bookモデル__を選択できるようにしています。-->
<!--選択したモデルをrangeとしてアクションに送っています。-->

<!--<%#= f.select :search, options_for_select([["完全一致","perfect_match"]以下略]) %>-->
<!--検索手法を定義しています。-->
<!--今回のようにカンマ区切りで複数定義することができます。-->
<!--選択した検索手法をsearchとしてアクションに送っています。-->

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <tr>
        <th>name</th>
        <th>introduction</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.introduction %></td>
        </tr>
      <% end %>
      <tr>
        <td><%#= link_to 'Show', user_path(user.id) %></td>
      </tr>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
      <tr>
        <th>image</th>
        <th>title</th>
        <th>opinion</th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <td>
            <!--画像をリンクに紐づけるときは、do,endで囲う-->
            <%= link_to(book.user) do %>
             <%= image_tag book.user.get_profile_image(50,50) %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>